version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=QdYx3D5y
  migration:
    build: .
    image: coderdojo/cd-warehouse-procedures
    command: [ "python", "./etl/main.py", "--dev" ]
    depends_on:
      - db
    volumes:
      - ./config:/usr/src/app/config
      - ./sql:/usr/src/app/sql
      - ./etl:/usr/src/app/etl
      - ./dumps:/db

volumes:
  pg-data:
