version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=QdYx3D5y
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - AWS_ACCESS=
      - AWS_SECRET=
      - PGPASSWORD=QdYx3D5y
      - PGUSER=platform
      - PGHOST=db

volumes:
  pg-data:
