version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=platform
      - POSTGRES_PASSWORD=QdYx3D5y
  migration:
    build: .
    image: coderdojo/cd-warehouse-procedures
    depends_on:
      - db
    volumes:
      - ./config:/usr/src/app/config
      - ./etl:/usr/src/app/etl

volumes:
  pg-data:
